config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :cover_image, only: [:destroy], module: :posts
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true

  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/posts/cover_images_controller.rb
class Posts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier
  
  before_action :authenticate_user!
  before_action :set_post

  def destroy
    @post.cover_image.purge_later

    respond_to do |format|
      format.html { redirect_to edit_post_path(@post) } 
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@post, :cover_image)) }
    end
  end

  private

  def set_post
      @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]
  
  # GET /posts or /posts.json
  def index
    @posts = user_signed_in? ? Post.sorted : Post.published.sorted
    @pagy, @posts = pagy(@posts)
  rescue Pagy::OverflowError
    redirect_to root_path(page: 1)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = user_signed_in? ? Post.find(params[:id]) : @post = Post.published.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :published_at, :cover_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_header.html.erb
<header class="flex justify-evenly items-center mx-auto font-bold shadow-md py-3 border-b border-black dark:border-white">
  <nav>
    <button><%= link_to "Home", posts_path %></button>
  </nav>

  <nav class=" flex gap-x-8">
    
    <a href="https://github.com/fernandodxx" target="_blank">Github</a>
    <a href="https://www.linkedin.com/in/fernando-santos-b780081a0?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BgE8Dlh%2FyQr2YvR16o3bOfg%3D%3D" target="_blank">Linkedin</a>
    <% if user_signed_in? %>
   
      <%#= link_to "Profile", edit_user_registration_path %>
      <a> 
        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      </a>
    <% else %>
      <a><%= link_to "Login", new_user_session_path %></a>
      <%#= link_to "Sign Up", new_user_registration_path %>
    <% end %>
  </nav>
</header>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>Fernando-Santos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= favicon_link_tag 'logo.jpg' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="dark:bg-slate-900 dark:text-slate-400">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
     
    <%= render "layouts/header" %>
     
    <main class="container mx-auto mt-28 px-5 flex ">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cover_image %>
    <% if post.cover_image.present? %>
      <div id="<%= dom_id(post, :cover_image) %>">
        <%= image_tag post.cover_image, class: "w-1/2"  %>
        <%= link_to "Delete image", post_cover_image_path(post), 
                      data: { turbo_method: :delete,
                      turbo_confirm: "Are you sure?" } %>
      </div>
    <% end %>
    <%= form.file_field :cover_image%>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.rich_text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full " %>
  </div>

  <div class="my-5">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, include_blank: true%>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<nav id="<%= dom_id post %>" class=" rounded-md p-3 shadow-lg px-8 border-l-4 border-black dark:border-white">

  <% if action_name != "show" %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z" />
    </svg>
  <% end %>

  <h1 class="font-bold text-2xl py-5 ">
    <%= link_to post.title, post, class:"block"%>
  </h1>

  <% if action_name != "show" %>
    <p><%= truncate(post.content.to_plain_text, length: 130) %></p>
  <% end %>

  <% if action_name != "index" %>
    
    <p class="">
      <%= post.content %>
    <p>
  <% end %>
  
  <% if post.draft? %>
      <div class="bg-red-300 p2 rounded"> Draft</div>
  <% elsif post.scheduled? %>
      <div class="bg-yellow-100 p2 rounded"> schedule</div>
  <% end %>
 
  <% if user_signed_in? %>
    <% if action_name != "show" %>
      <%= link_to "Edit this post", edit_post_path(post) %>
    <% end %>
  <% end %>
</nav>
<br>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<section class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="flex font-bold text-4xl items-center gap-4">Leia meu Blog 
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25" />
      </svg>
    </h1>
    <% if user_signed_in? %>
      <%= link_to "New post", new_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="posts" class="min-w-full py-12">
    <%= render @posts %>
  </div>
  <div class="my-16">
    <%== pagy_nav(@pagy ) if @pagy.pages > 1%>
  </div>
</section>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    
    <div class="px-8">
      <%= render @post %>
    <div>

    </div>

   
    <% if user_signed_in? %>
      <div class="inline-block text-white"><%= link_to "Back", posts_path, class: "ml-2 rounded-lg py-2 px-3 bg-green-600 font-medium" %></div>
      <div class="inline-block text-white"><%= button_to "Destroy", post_path(@post), method: :delete, class:"ml-2 rounded-lg py-1 px-3 bg-red-600 font-medium"%></div>
    <% else %>
      <div class="inline-block text-white"><%= link_to "Back", posts_path, class: "ml-2 rounded-lg py-2 px-3 bg-gray-100 font-medium" %></div>
    <%end%>
</div>